### ISSUE TITLE
invalid file name in page-sets.module.ts

### ISSUE THREAD

**Issue by amrnablus** [Magillem/generator-jhipster-pages#10]
in page-sets.module.ts, i created a new set named "Create", here's what got generated
`import { ThermostatsolutionsCreateModule } from './create/Create.module';`
should be 
`import { ThermostatsolutionsCreateModule } from './create/create.module';` (small letter c)

if you're testing on windows or mac you'd probably miss it

**Comment by Dufgui** [comment]
please test with the 2.0.1, normaly it's fixed

**Comment by Dufgui** [comment]
I will reopen if not
