### ISSUE TITLE
Canot find _page_es.json error

### ISSUE THREAD

**Issue by poolebu** [Magillem/generator-jhipster-pages#11]
Hello, I wanted to try your module, but it's not working for me:

![captura de pantalla 2018-01-07 a la s 6 50 29 p m](https://user-images.githubusercontent.com/4500001/34652228-b72590de-f3db-11e7-9c09-fd7f10ab6dc0.png)

  Error is
```
ERROR! Copying template client/i18n/_page_es.json failed. [Error: ENOENT: no such file or directory, open '/Users/poolebu/.npm-packages/lib/node_modules/generator-jhipster-pages/generators/app/templates/client/i18n/_page_es.json']
```

**Comment by Dufgui** [comment]
hello, it's fixed i think. try 2.0.2 version please
