### ISSUE TITLE
Unable to find src/main/webapp/app/layouts/navbar/navbar.component.html or missing required jhipster-needle

### ISSUE THREAD

**Issue by abhayc77** [Magillem/generator-jhipster-pages#15]
With Jhipster 4.14 I am getting the error. The file is present but something else is not right. I had chosen to add a new page which loads and saves data to server

**Comment by Dufgui** [comment]
I will take a look at it

**Comment by abhayc77** [comment]
I checked with 4.11 and it works there. I think this is the Angular 4 to Angular 5 migration issue. Some naming convention for variables and path have changed from 4 to 5 and that is likely to be causing the issue.

**Comment by Dufgui** [comment]
In fact this file still exist in angular 4.14. I test and I found many
problem du to angular 5 migration but not this one

**Comment by Dufgui** [comment]
could you provide your yo-rc.json file just to understand the problem please?

**Comment by abhayc77** [comment]
Here it is
[yo-rc.json.txt](https://github.com/Magillem/generator-jhipster-pages/files/1739793/yo-rc.json.txt)

**Comment by abhayc77** [comment]
Do you plan to release angualr 5 version sometime soon?

**Comment by Dufgui** [comment]
i am testing it, and after i release. So probably this weekend or the next one. I already do a patch with a part of migration

**Comment by Dufgui** [comment]
i cannot reproduce this error but fix others... I close this issue because i cannot reproduce. I thinks your project have some missing file from jhipster standard generator. Please regenerate your project.
for the rest of angular 5. I still work on it

**Comment by abhayc77** [comment]
sure ...

**Comment by Dufgui** [comment]
Angular 5 is delivered by 2.0.4 release.
