### ISSUE TITLE
Empty pages generated

### ISSUE THREAD

**Issue by davidishee** [Magillem/generator-jhipster-pages#17]
I tried to create a new page to load and save data from a server. I'm using JHipster 4.13.3 with AngularX (as the yo-rc.json calls it), yarn v1.3.2, node 8.9.4. Here is how I ran the generator:

```
Welcome to the JHipster pages generator! v2.0.3

? Create page in the following page set: UsageDataPageset
? Which kind of page you want to add? Load and Save data to server
? Enter the page name: UsageData
? Enter the page glyphicon name (see https://getbootstrap.com/components/): glyphicon-upload
```
I see the page set on the nav bar, but it has no content. I was expecting a form or GUI buttons or something...

Also, the glyph icon isn't showing up. Did I specify it incorrectly?

**Comment by davidishee** [comment]
I figured out the JHipster pages are using Font Awesome, so the suggested link to the Bootstrap glyphicons was misleading.

**Comment by Dufgui** [comment]
Upload is enough for the icon. Strange for the rest. Have you seen any
errors in your web js console ? (Firebug or standard)

Could you provide your yo rc file please ?


Le ven. 23 févr. 2018 à 17:57, davidishee <notifications@github.com> a
écrit :

**Comment by davidishee** [comment]
I am seeing errors in the console. I'm new at front end development. 

```
ERROR TypeError: Cannot read property 'bind' of undefined
    at Object.eval [as updateDirectives] (UsageDataComponent.html:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js?593e:14690)
    at checkAndUpdateView (core.js?593e:13837)
    at callViewAction (core.js?593e:14188)
    at execEmbeddedViewsAction (core.js?593e:14146)
    at checkAndUpdateView (core.js?593e:13838)
    at callViewAction (core.js?593e:14188)
    at execComponentViewsAction (core.js?593e:14120)
    at checkAndUpdateView (core.js?593e:13843)
    at callViewAction (core.js?593e:14188)
```

**Comment by davidishee** [comment]
yo rc file:
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.chooser.electricity"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "ElectricityChooser",
    "packageName": "com.chooser.electricity",
    "packageFolder": "com/chooser/electricity",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "41a601d6ba0c0f1ba6d1ef175c7c5fdef6c237ef",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "cacheProvider": "ehcache",
    "enableHibernateCache": true
  },
  "generator-jhipster-pages": {
    "promptValues": {
      "pageSet": "UsageDataPageset",
      "pageType": "loadAndSaveToServer"
    }
  }
}
```

**Comment by davidishee** [comment]
I'll also mention that I didn't implement the server code yet, so no data was available from the server and I didn't flush out the model classes. I have an existing end-point I want to use so I'll work on using it instead so I'll have some data.

**Comment by Dufgui** [comment]
ok so i found a bug on ts side, but you don't have this one. It's just normal.
My tools have for goal to make plumbery, so I create service on server and client side. But for this option I provide no default web page because I don't know if it's a form or a table. And the model have no field. So the displayed page is empty. You need to implement the ts loadAll by calling the ts entity service and use it on html side.

And then you can call other ts entity service to push data to server. 
And same thing, you must implement the server side after.

The goal of this module is just don't implement the plumbery (ts service and java web service) for not entity pages . So i push and release my small fix
