### ISSUE TITLE
Error! copying template.

### ISSUE THREAD

**Issue by fabidick22** [Magillem/generator-jhipster-pages#7]
This error happens when I created my jhipster project with native language in Spanish. (with "angularjs" and English as the native language works correctly)

`ERROR! Copying template client/angular/src/main/webapp/app/pages/_page-set.service.ts failed. [Error: ENOENT: no such file or directory, open '/usr/lib/node_modules/generator-jhipster-pages/generators/app/templates/client/angular/src/main/webapp/app/pages/_page-set.service.ts']
`
![jhipster1](https://user-images.githubusercontent.com/8176821/31916916-949f6a1e-b81a-11e7-819d-99ee831dfb98.png)

the same error happens when I try to generate a page with "angular 4" independently of the native language.

Thanks..

**Comment by Dufgui** [comment]
This error is normal. It's because i am not yet compatible with angular 4.
_page-set.service.ts is an angular 4 files wich is in development.

**Comment by Dufgui** [comment]
see #1
