### ISSUE TITLE
generator-jhipster-pages  Glyphicons error

### ISSUE THREAD

**Issue by KevinArdon** [Magillem/generator-jhipster-pages#9]
****ERROR! Copying template client/angular/src/main/webapp/app/pages/_page-set.service.ts failed. [Error: ENOENT: no such file or directory, open '/home/yopo/Escritorio/log/node_modules/generator-jhipster-pages/generators/app/templates/client/angular/src/main/webapp/app/pages/_page-set.service.ts']**

_Motivation for or Use Case_

When initializing the page generator to create a blank page, the following questions are answered without problem: Create page in the following pages set: Create a new pages set
? Create page set with the following name: test
? Which king of page you want to add? Client Only
? Enter the page name: test

However, when answering "? Enter the page glyphicon name" for example with "glyphicon glyphicon-eur" and hitting enter, the error happens right after that. I tried looking for _page-set.service.ts following the route described but it's nowhere to be found, when getting to the end of the route I can only find _page.module.ts., then I tried creating the page just to see what happens but it keeps asking for more files like _page-set.route.ts, etc and getting nowhere (naturally, those files where deleted after that).

_Reproduce the error_

Enter "yo jhipster-pages"
Answer questions (it has examples on another try):
Create page in the following pages set: Create a new pages set
? Create page set with the following name: Test
? Which king of page you want to add? Client Only
? Enter the page name: Test
? Enter the page glyphicon name (see https://getbootstrap.com/components/): pages glyphicons-87-display.png
Error jhipster-pages

_JHipster Version(s)_

4.10.0

_JHipster configuration_

Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator
JHipster Version(s)

/home/yopo
└── (empty)

cat: no such file or directory: .yo-rc.json
JHipster configuration, a .yo-rc.json file generated in the root folder
.yo-rc.json file
JDL for the Entity configuration(s) entityName.json files generated in the .jhipster directory
JDL entity definitions
Environment and Tools

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.11.0
node: v6.11.4
npm: 5.5.1
bower: 1.8.2
gulp:
[11:52:36] CLI version 1.4.0
yeoman: 2.0.0
yarn: 1.2.1

_Operating System_

Ubuntu 17.04

**Comment by Dufgui** [comment]
it's a .ts files so you used angular 4. In fact, my module is not yet compatible with angular 4.
See #1 
It's in dev
